services:
  frontend:
    build: ./frontend 
    ports:
      - "8081:8081"
    networks:
      - restful-api-perpustakaan
    
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - restful-api-perpustakaan
    volumes:
      - db-prod-data:/var/www/backend/database/data

networks:
  restful-api-perpustakaan:
    driver: bridge

volumes:
  db-prod-data: